networks:
    alaparicnet:
        name: alaparicnet
        driver: bridge
services:
    nginx:
        container_name: nginx
        build: ./requirements/nginx
        image: nginx
        ports:
            - "443:443"
        volumes:
            - wordpress_data:/var/www/html
        networks:
            - alaparicnet
        restart: always
    wordpress:
        container_name: wordpress
        build: ./requirements/wordpress
        image: wordpress
        depends_on:
            - mariadb
        volumes:
            - wordpress_data:/var/www/html
        env_file:
            - .env
        networks:
            - alaparicnet
        restart: always
    mariadb:
        container_name: mariadb
        build:
            context: ./requirements/mariadb
        image: mariadb
        volumes:
            - mariadb_data:/var/lib/mysql
        env_file:
            - .env
        networks:
            - alaparicnet
        restart: always
