version: "3.8"

services:
    nginx:
        container_name: nginx
        build:
            context: ./requirements/nginx
        image: alaparic_nginx
        env_file:
            - .env
        ports:
            - "443:80"
        volumes:
            - wordpress:/wordpress
        networks:
            - alaparicnet
        restart: always
        depends_on:
            - wordpress
    mariadb:
        container_name: mariadb
        build:
            context: ./requirements/mariadb
        image: alaparic_mariadb
        env_file:
            - .env
        expose:
            - "3306"
        volumes:
            - db:/var/lib/mysql
        networks:
            - alaparicnet
        restart: always
    wordpress:
        depends_on:
            - mariadb
        container_name: wordpress
        build:
            context: ./requirements/wordpress
        image: alaparic_wordpress
        env_file:
            - .env
        expose:
            - "9000"
        volumes:
            - wordpress:/wordpress
        networks:
            - alaparicnet
        restart: always

networks:
    alaparicnet:
        name: alaparicnet
        driver: bridge

volumes:
    db:
        driver: local
        driver_opts:
            type: none
            device: ~/inception/db
            o: bind
    wordpress:
        driver: local
        driver_opts:
            type: none
            device: ~/inception/wordpress
            o: bind
