networks:
    alaparicnet:
        name: alaparicnet
        driver: bridge
services:
    nginx:
        container_name: nginx
        build: ./requirements/nginx
        image: alaparic_nginx
        ports:
            - "443:80"
        networks:
            - alaparicnet
        restart: always
