networks:
    alaparicnet:
        name: alaparicnet
        driver: bridge
services:
    nginx:
        container_name: nginx
        build: ./requirements/nginx
        image: alaparic_nginx
        ports:
            - "443:80"
        networks:
            - alaparicnet
        restart: always
    mariadb:
        container_name: mariadb
        build:
            context: ./requirements/mariadb
        image: alaparic_mariadb
        env_file:
            - .env
        networks:
            - alaparicnet
        restart: always
    wordpress:
        container_name: wordpress
        build:
            context: ./requirements/wordpress
        image: alaparic_wordpress
        env_file:
            - .env
        networks:
            - alaparicnet
        restart: always
